# SPDX-License-Identifier: GPL-2.0-or-later

PACKAGE_NAME="odyssey-ddc"
PACKAGE_VERSION="0.1.0"

MAKE[0]="make KVERSION=${kernelver}"
CLEAN="make clean"

BUILT_MODULE_NAME[0]="odyssey_ddc"
DEST_MODULE_LOCATION[0]="/kernel/drivers/video/backlight"

AUTOINSTALL="yes"
